#!/usr/bin/env sh
# NOTE: this file uses HARD TABS.
# vim: set ts=4 sw=4 sts=4 noet:
set -e

get_port() {
	if host_n_port=$(docker compose port "$@")
	then
		echo "${host_n_port##*:}"
	else
		echo "ERROR: failed to find port for $*"
		return 1
	fi
}

uv sync --all-groups --all-extras --frozen

docker compose down --remove-orphans --volumes
docker compose up -d --wait

logs_port=$(get_port loki 3100)
trace_port=$(get_port jaeger 4317)
cat>.env<<EOF
OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=http://127.0.0.1:$logs_port/otlp/v1/logs
OTEL_EXPORTER_OTLP_LOGS_PROTOCOL=http/protobuf
OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://127.0.0.1:$trace_port
OTEL_LOGS_EXPORTER=otlp
OTEL_METRICS_EXPORTER=none
OTEL_PROPOGATORS=baggage,tracecontext
OTEL_SERVICE_NAME=imbi-gateway
OTEL_TRACES_EXPORTER=otlp
EOF
